spring:
 datasource:
  url: jdbc:mysql://localhost/LOGOS?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: 1234
  jpa:
    hibernate:
        ddl-auto: update
        show-sql: true