spring:
  datasource:
    url: jdbc:mysql://localhost/LOGOS?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENHA_DE_APP}
    password: ${PASSWORD_SENHA_DE_APP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
server:
  port: 8080