CREATE TABLE PESSOA_ENDERECO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PESSOA_ID BIGINT NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    NUMERO INT NOT NULL,
    COMPLEMENTO VARCHAR(255),
    PRINCIPAL BOOLEAN NOT NULL,
    FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA(ID),
    FOREIGN KEY (CEP) REFERENCES ENDERECO(CEP)
);