CREATE TABLE LOGOS.ENDERECO (
    CEP VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    LOCALIDADE VARCHAR(45) NOT NULL,
    UF VARCHAR(3) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    DDD VARCHAR(6) NOT NULL,
    PRIMARY KEY (CEP)
);
